import { Product, Category } from '@/types/product'

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-men',
    name: 'MEN',
    slug: 'men',
    description: 'Elevated everyday essentials & custom tees.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    altText: 'Man wearing Moodifys minimal apparel',
    buttonText: 'SHOP MEN →',
    buttonUrl: '/shop/men',
    sortOrder: 1,
    isActive: true,
    isVisible: true,
  },
  {
    id: 'cat-women',
    name: 'WOMEN',
    slug: 'women',
    description: 'Effortless minimalist pieces for every mood.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    altText: 'Woman wearing Moodifys editorial collection',
    buttonText: 'SHOP WOMEN →',
    buttonUrl: '/shop/women',
    sortOrder: 2,
    isActive: true,
    isVisible: true,
  },
  {
    id: 'cat-kids',
    name: 'KIDS',
    slug: 'kids',
    description: 'Comfort meets playful character everyday.',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80',
    altText: 'Kids wearing organic cotton custom apparel',
    buttonText: 'SHOP KIDS →',
    buttonUrl: '/shop/kids',
    sortOrder: 3,
    isActive: true,
    isVisible: true,
  },
  {
    id: 'cat-accessories',
    name: 'ACCESSORIES',
    slug: 'accessories',
    description: 'Small personalized details. Big mood.',
    imageUrl: 'https://images.unsplash.com/photo-1529720317453-c8da503f2051?w=800&auto=format&fit=crop&q=80',
    altText: 'Archival caps and canvas tote accessories',
    buttonText: 'SHOP ACCESSORIES →',
    buttonUrl: '/shop/accessories',
    sortOrder: 4,
    isActive: true,
    isVisible: true,
  },
]

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-classic-tee',
    name: 'CLASSIC 240GSM TEE',
    slug: 'classic-240gsm-tee',
    description: 'The definitive Moodifys foundation piece. Crafted from 240GSM ultra-dense combed organic cotton with a structured ribbed collar and relaxed tailored drape. The primary canvas for your mood.',
    categoryId: 'cat-tshirts',
    categoryName: 'T-SHIRTS',
    basePrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
    isCustomizable: true,
    isActive: true,
    isNew: true,
    colors: [
      { name: 'Black', hex: '#090808' },
      { name: 'Charcoal', hex: '#302F2E' },
      { name: 'Off White', hex: '#E1E0DC' },
      { name: 'Pure White', hex: '#FFFFFF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    materials: '100% Combed Compact Cotton, 240 GSM single jersey',
    fit: 'True to size modern relaxed fit',
    careInstructions: 'Machine wash cold inside out. Do not tumble dry over print.',
  },
  {
    id: 'prod-oversized-tee',
    name: 'OVERSIZED STUDIO TEE',
    slug: 'oversized-studio-tee',
    description: 'Aggressively proportioned drop-shoulder silhouette with wide sleeves and a relaxed streetwear box crop.',
    categoryId: 'cat-tshirts',
    categoryName: 'T-SHIRTS',
    basePrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
    isCustomizable: true,
    isActive: true,
    isNew: false,
    colors: [
      { name: 'Black', hex: '#090808' },
      { name: 'Warm Gray', hex: '#BEBDBB' },
      { name: 'Off White', hex: '#E1E0DC' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    materials: '100% Cotton, 260 GSM heavyweight',
    fit: 'Oversized drop-shoulder box fit',
    careInstructions: 'Cold machine wash, hang dry in shade.',
  },
  {
    id: 'prod-heavyweight-hoodie',
    name: 'HEAVYWEIGHT BOX HOODIE',
    slug: 'heavyweight-box-hoodie',
    description: '450GSM French Terry cotton pullover hoodie featuring double-layer hood construction, hidden side pockets, and zero drawstrings for pure minimalist aesthetics.',
    categoryId: 'cat-hoodies',
    categoryName: 'HOODIES',
    basePrice: 2199,
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
    isCustomizable: false,
    isActive: true,
    isNew: true,
    colors: [
      { name: 'Black', hex: '#090808' },
      { name: 'Charcoal', hex: '#302F2E' },
      { name: 'Off White', hex: '#E1E0DC' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    materials: '100% French Terry Cotton, 450 GSM',
    fit: 'Boxy streetwear fit',
    careInstructions: 'Wash cold inside out. Flat dry.',
  },
  {
    id: 'prod-raw-sweatshirt',
    name: 'RAW HEM CREWNECK SWEATSHIRT',
    slug: 'raw-hem-crewneck-sweatshirt',
    description: 'Minimalist drop-shoulder crewneck featuring raw seam finishes and brushed cotton interior.',
    categoryId: 'cat-sweatshirts',
    categoryName: 'SWEATSHIRTS',
    basePrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80',
    isCustomizable: false,
    isActive: true,
    isNew: false,
    colors: [
      { name: 'Charcoal', hex: '#302F2E' },
      { name: 'Warm Gray', hex: '#BEBDBB' },
      { name: 'Black', hex: '#090808' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    materials: '100% Brushed Terry, 380 GSM',
    fit: 'Relaxed fit',
    careInstructions: 'Machine wash delicate cold.',
  },
  {
    id: 'prod-canvas-tote',
    name: 'MONOCHROME CANVAS TOTE',
    slug: 'monochrome-canvas-tote',
    description: 'Heavyweight 16oz duck canvas tote bag with reinforced handles and interior zip pocket.',
    categoryId: 'cat-accessories',
    categoryName: 'ACCESSORIES',
    basePrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
    isCustomizable: false,
    isActive: true,
    isNew: true,
    colors: [
      { name: 'Off White', hex: '#E1E0DC' },
      { name: 'Black', hex: '#090808' },
    ],
    sizes: ['ONE SIZE'],
    materials: '100% Organic Heavyweight Duck Canvas 16oz',
    fit: 'Standard 42cm x 38cm capacity',
    careInstructions: 'Spot clean with cold water.',
  },
  {
    id: 'prod-archival-cap',
    name: 'ARCHIVAL 6-PANEL CAP',
    slug: 'archival-6-panel-cap',
    description: 'Unstructured low-profile 6-panel cap crafted from washed cotton twill with matte metal buckle slider.',
    categoryId: 'cat-accessories',
    categoryName: 'ACCESSORIES',
    basePrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
    hoverImageUrl: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800&auto=format&fit=crop&q=80',
    isCustomizable: false,
    isActive: true,
    isNew: false,
    colors: [
      { name: 'Black', hex: '#090808' },
      { name: 'Charcoal', hex: '#302F2E' },
    ],
    sizes: ['ADJUSTABLE'],
    materials: '100% Washed Cotton Twill',
    fit: 'Adjustable strap with brass closure',
    careInstructions: 'Hand wash cold.',
  },
]
